name: Trigger auto deployment for medeasecontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/medeasecontainer-AutoDeployTrigger-4ab13518-e619-420a-adc5-f66a44cbbd0b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MEDEASECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEDEASECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEDEASECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.MEDEASECONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEDEASECONTAINER_REGISTRY_PASSWORD }}
          containerAppName: medeasecontainer
          resourceGroup: DefaultResourceGroup-CID
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


